module.exports = {
    "skills": [
        {
            "level": 1,
            "name": "HTML",
            "name_uppercase": "HTML",
            "video": "https://www.youtube.com/watch?v=UB1O30fR-EE",
            "video_embed": "https://www.youtube.com/embed/UB1O30fR-EE",
            "resource_link1": "https://www.freecodecamp.org/learn/responsive-web-design/basic-html-and-html5/",
            "resource_link2": "https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics",
            "resource_link3": "https://internetingishard.com/html-and-css/semantic-html/",
            "foundation": ["None"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "CSS",
            "name_uppercase": "CSS",
            "video": "https://www.youtube.com/watch?v=yfoY53QXEnI",
            "video_embed": "https://www.youtube.com/embed/yfoY53QXEnI",
            "resource_link1": "https://www.freecodecamp.org/learn/responsive-web-design/basic-css/",
            "resource_link2": "https://css-tricks.com/guides/beginner/",
            "resource_link3": "https://www.htmldog.com/guides/css/beginner/",
            "foundation": ["HTML"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "Flexbox",
            "name_uppercase": "FLEXBOX",
            "video": "https://www.youtube.com/watch?v=k32voqQhODck32voqQhODc",
            "video_embed": "https://www.youtube.com/embed/k32voqQhODc",
            "resource_link1": "https://css-tricks.com/snippets/css/a-guide-to-flexbox/",
            "resource_link2": "https://flexboxfroggy.com/",
            "resource_link3": "https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox",
            "foundation": ["CSS"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "CSS Grid",
            "name_uppercase": "CSS GRID",
            "video": "https://www.youtube.com/watch?v=SPFDLHNm5KQ",
            "video_embed": "https://www.youtube.com/embed/SPFDLHNm5KQ",
            "resource_link1": "https://css-tricks.com/snippets/css/complete-guide-grid/",
            "resource_link2": "https://cssgridgarden.com/",
            "resource_link3": "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout",
            "foundation": ["CSS"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "Animations",
            "name_uppercase": "ANIMATIONS",
            "video": "https://www.youtube.com/watch?v=zHUpx90NerM",
            "video_embed": "https://www.youtube.com/embed/zHUpx90NerM",
            "resource_link1": "https://medium.com/engineerbabu/a-detailed-guide-to-css-animations-and-transitions-b544502c089c",
            "resource_link2": "https://css-tricks.com/almanac/properties/a/animation/",
            "resource_link3": "https://codeburst.io/a-guide-to-css-animation-part-1-8777f5beb1f8",
            "foundation": ["CSS"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "SCSS/SASS",
            "name_uppercase": "SCSS/SASS",
            "video": "https://www.youtube.com/watch?v=Zz6eOVaaelI",
            "video_embed": "https://www.youtube.com/embed/Zz6eOVaaelI",
            "resource_link1": "https://sass-lang.com/guide",
            "resource_link2": "https://www.freecodecamp.org/news/the-complete-guide-to-scss-sass-30053c266b23/",
            "resource_link3": "https://codeburst.io/intro-to-sass-386eb8f2e005",
            "foundation": ["CSS", "JavaScript"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "LESS",
            "name_uppercase": "LESS",
            "video": "https://www.youtube.com/watch?v=YD91G8DdUsw",
            "video_embed": "https://www.youtube.com/embed/YD91G8DdUsw",
            "resource_link1": "https://lesscss.org/",
            "resource_link2": "https://medium.com/matts-lambda-minutes/matts-lambda-minute-less-is-more-a-starter-s-guide-to-less-and-css-preprocessing-41b0ddd16eb7",
            "resource_link3": "https://tutorialzine.com/2015/07/learn-less-in-10-minutes-or-less",
            "foundation": ["CSS", "JavaScript"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "Styled Components",
            "name_uppercase": "STYLED COMPONENTS",
            "video": "https://www.youtube.com/watch?v=3SpAg5tr7Ws",
            "video_embed": "https://www.youtube.com/embed/3SpAg5tr7Ws",
            "resource_link1": "https://www.styled-components.com/docs/basics#getting-started",
            "resource_link2": "https://medium.com/styled-components/styled-components-getting-started-c9818acbcbbd",
            "resource_link3": "https://www.robinwieruch.de/react-styled-components",
            "foundation": ["CSS", "JavaScript", "React"],
            "track": ["frontend"]
        },
        {
            "level": 2,
            "name": "CSS Modules",
            "name_uppercase": "CSS MODULES",
            "video": "https://www.youtube.com/watch?v=w1GCB5D2EP8",
            "video_embed": "https://www.youtube.com/embed/w1GCB5D2EP8",
            "resource_link1": "https://www.triplet.fi/blog/practical-guide-to-react-and-css-modules/",
            "resource_link2": "https://www.javascriptstuff.com/css-modules-by-example/",
            "resource_link3": "https://css-tricks.com/css-modules-part-2-getting-started/",
            "foundation": ["CSS", "JavaScript", "React"],
            "track": ["frontend"]
        },
        {
            "level": 3,
            "name": "JavaScript",
            "name_uppercase": "JAVASCRIPT",
            "video": "https://www.youtube.com/watch?v=PkZNo7MFNFg",
            "video_embed": "https://www.youtube.com/embed/PkZNo7MFNFg",
            "resource_link1": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
            "resource_link2": "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/basic-javascript/",
            "resource_link3": "https://javascript.info/",
            "foundation": ["HTML", "CSS"],
            "track": ["language", "frontend", "backend"]
        },
        {
            "level": 4,
            "name": "NodeJS",
            "name_uppercase": "NODEJS",
            "video": "https://www.youtube.com/watch?v=TlB_eWDSMt4",
            "video_embed": "https://www.youtube.com/embed/TlB_eWDSMt4",
            "resource_link1": "https://nodejs.org/en/docs/guides/",
            "resource_link2": "https://developer.ibm.com/tutorials/learn-nodejs-tour-node/",
            "resource_link3": "https://itnext.io/introduction-to-node-js-a-beginners-guide-to-node-js-and-npm-eca9c408f9fe",
            "foundation": ["JavaScript"],
            "track": ["backend"]
        },
        {
            "level": 4,
            "name": "React",
            "name_uppercase": "REACT",
            "video": "https://www.youtube.com/watch?v=Ke90Tje7VS0",
            "video_embed": "https://www.youtube.com/embed/Ke90Tje7VS0",
            "resource_link1": "https://reactjs.org/docs/getting-started.html",
            "resource_link2": "https://scotch.io/starters/react/getting-started-with-react-2019-edition",
            "resource_link3": "https://www.freecodecamp.org/learn/front-end-libraries/react/",
            "foundation": ["JavaScript"],
            "track": ["frontend"]
        },
        {
            "level": 5,
            "name": "Testing",
            "name_uppercase": "TESTING",
            "video": "https://www.youtube.com/watch?v=r9HdJ8P6GQI",
            "video_embed": "https://www.youtube.com/embed/r9HdJ8P6GQI",
            "resource_link1": "https://medium.com/welldone-software/an-overview-of-javascript-testing-in-2019-264e19514d0a",
            "resource_link2": "https://www.youtube.com/watch?v=7r4xVDI2vho",
            "resource_link3": "https://www.youtube.com/watch?v=pJ349YntoIs",
            "foundation": ["JavaScript"],
            "track": ["frontend", "backend"]
        },
        {
            "level": 5,
            "name": "Express",
            "name_uppercase": "EXPRESS",
            "video": "https://www.youtube.com/watch?v=L72fhGm1tfE",
            "video_embed": "https://www.youtube.com/embed/L72fhGm1tfE",
            "resource_link1": "https://expressjs.com/en/starter/installing.html",
            "resource_link2": "https://flaviocopes.com/express/",
            "resource_link3": "https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs",
            "foundation": ["NodeJS"],
            "track": ["backend"]
        },
        {
            "level": 6,
            "name": "TypeScript",
            "name_uppercase": "TYPESCRIPT",
            "video": "https://www.youtube.com/watch?v=WBPrJSw7yQA",
            "video_embed": "https://www.youtube.com/embed/WBPrJSw7yQA",
            "resource_link1": "https://www.typescriptlang.org/docs/tutorial.html",
            "resource_link2": "https://www.valentinog.com/blog/typescript/",
            "resource_link3": "https://www.freecodecamp.org/news/the-definitive-typescript-handbook/",
            "foundation": ["JavaScript"],
            "track": ["language", "frontend", "backend"]
        },
        {
            "level": 6,
            "name": "Redux",
            "name_uppercase": "REDUX",
            "video": "https://www.youtube.com/watch?v=93p3LxR9xfM",
            "video_embed": "https://www.youtube.com/embed/93p3LxR9xfM",
            "resource_link1": "https://redux.js.org/introduction/getting-started",
            "resource_link2": "https://redux.js.org/introduction/learning-resources",
            "resource_link3": "https://www.freecodecamp.org/news/understanding-redux-the-worlds-easiest-guide-to-beginning-redux-c695f45546f6/",
            "foundation": ["React"],
            "track": ["frontend"]
        },
        {
            "level": 6,
            "name": "SQL",
            "name_uppercase": "SQL",
            "video": "https://www.youtube.com/watch?v=bEtnYWuo2Bw",
            "video_embed": "https://www.youtube.com/embed/bEtnYWuo2Bw",
            "resource_link1": "https://www.lifewire.com/sql-fundamentals-1019780",
            "resource_link2": "https://www.khanacademy.org/computing/computer-programming/sql",
            "resource_link3": "https://beginner-sql-tutorial.com/sql-commands.htm",
            "foundation": ["JavaScript"],
            "track": ["language", "backend"]
        },
        {
            "level": 6,
            "name": "NoSQL",
            "name_uppercase": "NOSQL",
            "video": "https://www.youtube.com/watch?v=uD3p_rZPBUQ",
            "video_embed": "https://www.youtube.com/embed/uD3p_rZPBUQ",
            "resource_link1": "https://www.guru99.com/nosql-tutorial.html",
            "resource_link2": "https://www.openmymind.net/2011/8/15/How-You-Should-Go-About-Learning-NoSQL/",
            "resource_link3": "https://www.geeksforgeeks.org/introduction-to-nosql/",
            "foundation": ["JavaScript"],
            "track": ["language", "backend"]
        },
        {
            "level": 7,
            "name": "MySQL",
            "name_uppercase": "MYSQL",
            "video": "https://www.youtube.com/watch?v=9ylj9NR0Lcg",
            "video_embed": "https://www.youtube.com/embed/9ylj9NR0Lcg",
            "resource_link1": "https://dev.mysql.com/doc/mysql-getting-started/en/",
            "resource_link2": "http://www.mysqltutorial.org/getting-started-with-mysql/",
            "resource_link3": "https://www.digitalocean.com/community/tutorials/a-basic-mysql-tutorial",
            "foundation": ["SQL"],
            "track": ["backend"]
        },
        {
            "level": 7,
            "name": "PostgreSQL",
            "name_uppercase": "PSOTGRESQL",
            "video": "https://www.youtube.com/watch?v=Dd2ej-QKrWY",
            "video_embed": "https://www.youtube.com/embed/Dd2ej-QKrWY",
            "resource_link1": "https://www.postgresql.org/docs/",
            "resource_link2": "http://www.postgresqltutorial.com/",
            "resource_link3": "https://medium.com/quick-code/top-tutorials-to-learn-postgresql-database-for-beginners-99ff0deb9f84",
            "foundation": ["SQL"],
            "track": ["backend"]
        },
        {
            "level": 7,
            "name": "MongoDB",
            "name_uppercase": "MONGODB",
            "video": "https://www.youtube.com/watch?v=-56x56UppqQ",
            "video_embed": "https://www.youtube.com/embed/-56x56UppqQ",
            "resource_link1": "https://docs.mongodb.com/guides/",
            "resource_link2": "https://www.freecodecamp.org/news/learn-mongodb-a4ce205e7739/",
            "resource_link3": "https://learntocodewith.me/posts/mongodb/",
            "foundation": ["NoSQL"],
            "track": ["backend"]
        },
        {
            "level": 8,
            "name": "Sequelize",
            "name_uppercase": "SEQUELIZE",
            "video": "https://www.youtube.com/watch?v=pxo7L5nd1gA",
            "video_embed": "https://www.youtube.com/embed/pxo7L5nd1gA",
            "resource_link1": "https://sequelize.org/v5/manual/getting-started.html",
            "resource_link2": "https://codeforgeek.com/getting-started-sequelize-postgresql/",
            "resource_link3": "https://www.robinwieruch.de/postgres-express-setup-tutorial",
            "foundation": ["SQL"],
            "track": ["backend"]
        },
        {
            "level": 8,
            "name": "Mongoose",
            "name_uppercase": "MONGOOSE",
            "video": "https://www.youtube.com/watch?v=WDrU305J1yw",
            "video_embed": "https://www.youtube.com/watch?v=WDrU305J1yw",
            "resource_link1": "https://mongoosejs.com/docs/",
            "resource_link2": "https://www.freecodecamp.org/news/introduction-to-mongoose-for-mongodb-d2a7aa593c57/",
            "resource_link3": "https://scotch.io/tutorials/using-mongoosejs-in-node-js-and-mongodb-applications",
            "foundation": ["MongoDB"],
            "track": ["backend"]
        },
    ]
}
